import { Shipment, InventoryItem, InventoryLedgerEntry, CaseRecord, Product } from '../types';
import { getTodayString, addDays } from './dateUtils';
import { calculateShipmentMetrics } from './statusCalculator';

export function generateDemoData(simulatedToday?: string): {
  shipments: Shipment[];
  inventory: InventoryItem[];
  ledger: InventoryLedgerEntry[];
  cases: CaseRecord[];
  products: Product[];
} {
  const today = simulatedToday || getTodayString();

  // Helper to get relative date
  const relDate = (daysDiff: number) => addDays(today, daysDiff);

  const products: Product[] = [
    {
      sku: 'PET1005-B-M',
      itemId: 'WMT-ITEM-550192',
      gtin: '008100523401',
      productName: 'Pet Ergonomic Mesh Dog Harness (Medium / Blue)',
      productType: 'Pet Supplies',
      safetyStock: 80,
      minStock: 40,
      maxStock: 500,
      targetStock: 250,
      recent30DaysSales: 185,
    },
    {
      sku: 'HOME-ORG-302',
      itemId: 'WMT-ITEM-781902',
      gtin: '008100523402',
      productName: 'Stackable Acrylic Closet Storage Bins 4-Pack',
      productType: 'Home Storage',
      safetyStock: 120,
      minStock: 60,
      maxStock: 600,
      targetStock: 350,
      recent30DaysSales: 240,
    },
    {
      sku: 'TECH-CAB-09',
      itemId: 'WMT-ITEM-310492',
      gtin: '008100523403',
      productName: 'Braided USB-C Fast Charging Cable (6.6ft / 2-Pack)',
      productType: 'Consumer Electronics',
      safetyStock: 150,
      minStock: 80,
      maxStock: 800,
      targetStock: 400,
      recent30DaysSales: 310,
    },
    {
      sku: 'OUT-CAMP-081',
      itemId: 'WMT-ITEM-904122',
      gtin: '008100523404',
      productName: 'Ultralight Inflatable Camping Sleeping Pad',
      productType: 'Outdoor & Sports',
      safetyStock: 50,
      minStock: 25,
      maxStock: 300,
      targetStock: 150,
      recent30DaysSales: 75,
    },
    {
      sku: 'BEAUTY-OIL-50',
      itemId: 'WMT-ITEM-449102',
      gtin: '008100523405',
      productName: 'Organic Cold-Pressed Rosehip Seed Facial Oil 50ml',
      productType: 'Beauty & Personal Care',
      safetyStock: 90,
      minStock: 45,
      maxStock: 450,
      targetStock: 200,
      recent30DaysSales: 160,
    },
    {
      sku: 'KITCH-SIL-6P',
      itemId: 'WMT-ITEM-612849',
      gtin: '008100523406',
      productName: 'Heat-Resistant Silicone Cooking Utensils Set (6-Piece)',
      productType: 'Kitchen & Dining',
      safetyStock: 100,
      minStock: 50,
      maxStock: 500,
      targetStock: 300,
      recent30DaysSales: 195,
    },
  ];

  // 8 Specific Prompt Scenarios + Extra realistic Walmart shipments
  const rawShipments: Partial<Shipment>[] = [
    // Scenario 1: 全部接收 (Ship 100, Received 100 -> 正常 无差异 无需Case)
    {
      id: '9741694WFA',
      shipmentName: '9741694WFA-PHX1-2026',
      shipDate: relDate(-20),
      eta: relDate(-14),
      arrivalDate: relDate(-13),
      fc: 'PHX1 (Phoenix, AZ)',
      tracking: '1Z999AA10123456781',
      carrier: 'UPS Freight',
      notes: '【场景1：全部接收】已全额签收清点完毕，无差异',
      source: 'Demo Data',
      items: [
        {
          shipmentId: '9741694WFA',
          sku: 'PET1005-B-M',
          itemId: 'WMT-ITEM-550192',
          gtin: '008100523401',
          productName: 'Pet Ergonomic Mesh Dog Harness (Medium / Blue)',
          productType: 'Pet Supplies',
          shipQty: 100,
          cartons: 5,
          qtyPerCarton: 20,
          receivedQty: 100,
          receivedCartons: 5,
          discrepancyQty: 0,
          receivedDate: relDate(-12),
          source: 'Walmart Inbound Template',
        },
      ],
    },

    // Scenario 2: 部分接收 (Ship 100, Received 80 -> 差异20)
    {
      id: '8839201KDL',
      shipmentName: '8839201KDL-IND1-2026',
      shipDate: relDate(-8),
      eta: relDate(-4),
      arrivalDate: relDate(-4),
      fc: 'IND1 (Plainfield, IN)',
      tracking: '1Z999AA10123456782',
      carrier: 'FedEx Freight',
      notes: '【场景2：部分接收】到仓4天，接收80件，待剩余20件清点',
      source: 'Demo Data',
      items: [
        {
          shipmentId: '8839201KDL',
          sku: 'KITCH-SIL-6P',
          itemId: 'WMT-ITEM-612849',
          gtin: '008100523406',
          productName: 'Heat-Resistant Silicone Cooking Utensils Set (6-Piece)',
          productType: 'Kitchen & Dining',
          shipQty: 100,
          cartons: 10,
          qtyPerCarton: 10,
          receivedQty: 80,
          receivedCartons: 8,
          discrepancyQty: 20,
          receivedDate: relDate(-3),
          source: 'Walmart Inbound Template',
        },
      ],
    },

    // Scenario 3: 到仓3天 (差异20，到仓3天 -> 还有7天达到Case条件)
    {
      id: '7619283TXA',
      shipmentName: '7619283TXA-CLT1-2026',
      shipDate: relDate(-6),
      eta: relDate(-3),
      arrivalDate: relDate(-3),
      fc: 'CLT1 (Charlotte, NC)',
      tracking: '1Z999AA10123456783',
      carrier: 'RL Carriers',
      notes: '【场景3：到仓3天】短少20件，还需7天达到Case处理条件',
      source: 'Demo Data',
      items: [
        {
          shipmentId: '7619283TXA',
          sku: 'TECH-CAB-09',
          itemId: 'WMT-ITEM-310492',
          gtin: '008100523403',
          productName: 'Braided USB-C Fast Charging Cable (6.6ft / 2-Pack)',
          productType: 'Consumer Electronics',
          shipQty: 100,
          cartons: 4,
          qtyPerCarton: 25,
          receivedQty: 80,
          receivedCartons: 4,
          discrepancyQty: 20,
          receivedDate: relDate(-2),
          source: 'Walmart Inbound Template',
        },
      ],
    },

    // Scenario 4: 到仓10天 (差异45，到仓10天 -> 可以开Case)
    {
      id: '6528194MNO',
      shipmentName: '6528194MNO-GVL1-2026',
      shipDate: relDate(-16),
      eta: relDate(-10),
      arrivalDate: relDate(-10),
      fc: 'GVL1 (Greenville, SC)',
      tracking: '1Z999AA10123456784',
      carrier: 'Estes Express',
      notes: '【场景4：到仓10天】今日正好满10天！差异45件，达到Case开启条件',
      source: 'Demo Data',
      items: [
        {
          shipmentId: '6528194MNO',
          sku: 'HOME-ORG-302',
          itemId: 'WMT-ITEM-781902',
          gtin: '008100523402',
          productName: 'Stackable Acrylic Closet Storage Bins 4-Pack',
          productType: 'Home Storage',
          shipQty: 200,
          cartons: 20,
          qtyPerCarton: 10,
          receivedQty: 155,
          receivedCartons: 16,
          discrepancyQty: 45,
          discrepancyTag: 'FC_SHORTAGE',
          discrepancyReason: 'FC清点差异45件，已满足10天立案条件',
          requiresFollowup: true,
          receivedDate: relDate(-8),
          source: 'Walmart Inbound Template',
        },
      ],
    },

    // Scenario 5: 超过10天未开Case (差异30，到仓15天，Case未开启 -> 严重提醒，已超过Case处理时间5天)
    {
      id: '5419208PLQ',
      shipmentName: '5419208PLQ-BFI1-2026',
      shipDate: relDate(-21),
      eta: relDate(-15),
      arrivalDate: relDate(-15),
      fc: 'BFI1 (Sumner, WA)',
      tracking: '1Z999AA10123456785',
      carrier: 'Old Dominion',
      notes: '【场景5：超期未开Case】到仓15天，超期5天未开Case！差异30件，请立即发起Claim',
      source: 'Demo Data',
      items: [
        {
          shipmentId: '5419208PLQ',
          sku: 'BEAUTY-OIL-50',
          itemId: 'WMT-ITEM-449102',
          gtin: '008100523405',
          productName: 'Organic Cold-Pressed Rosehip Seed Facial Oil 50ml',
          productType: 'Beauty & Personal Care',
          shipQty: 150,
          cartons: 15,
          qtyPerCarton: 10,
          receivedQty: 120,
          receivedCartons: 12,
          discrepancyQty: 30,
          discrepancyTag: 'FC_SHORTAGE',
          discrepancyReason: '少收3箱共30件，严重超期未建Case',
          requiresFollowup: true,
          receivedDate: relDate(-13),
          source: 'Walmart Inbound Template',
        },
      ],
    },

    // Scenario 6: Case已开启 (差异60，到仓16天，Case已开启 -> 状态 Case Processing)
    {
      id: '4392018QRT',
      shipmentName: '4392018QRT-MCI1-2026',
      shipDate: relDate(-22),
      eta: relDate(-16),
      arrivalDate: relDate(-16),
      fc: 'MCI1 (Edgerton, KS)',
      tracking: '1Z999AA10123456786',
      carrier: 'TForce Freight',
      caseId: 'WMT-CASE-202608-019',
      caseStatus: 'In Review',
      notes: '【场景6：Case已开启】Walmart调查中，已提供POD与装箱单',
      source: 'Demo Data',
      items: [
        {
          shipmentId: '4392018QRT',
          sku: 'OUT-CAMP-081',
          itemId: 'WMT-ITEM-904122',
          gtin: '008100523404',
          productName: 'Ultralight Inflatable Camping Sleeping Pad',
          productType: 'Outdoor & Sports',
          shipQty: 180,
          cartons: 18,
          qtyPerCarton: 10,
          receivedQty: 120,
          receivedCartons: 12,
          discrepancyQty: 60,
          discrepancyTag: 'PENDING_INVESTIGATION',
          discrepancyReason: 'FC核实中，已上传POD签收单',
          requiresFollowup: true,
          receivedDate: relDate(-14),
          source: 'Walmart Inbound Template',
        },
      ],
    },

    // Scenario 7: Walmart补收 (原发货100接收80，更新后接收100 -> 差异0，Fully Received，Case自动转为Resolved)
    {
      id: '3281092WZX',
      shipmentName: '3281092WZX-IND1-2026',
      shipDate: relDate(-25),
      eta: relDate(-18),
      arrivalDate: relDate(-18),
      fc: 'IND1 (Plainfield, IN)',
      tracking: '1Z999AA10123456787',
      carrier: 'UPS Freight',
      caseId: 'WMT-CASE-202608-011',
      caseStatus: 'Resolved',
      notes: '【场景7：Walmart补收】FC初次接收80件，后在暂存区清点补收20件，现已全收闭环',
      source: 'Demo Data',
      items: [
        {
          shipmentId: '3281092WZX',
          sku: 'PET1005-B-M',
          itemId: 'WMT-ITEM-550192',
          gtin: '008100523401',
          productName: 'Pet Ergonomic Mesh Dog Harness (Medium / Blue)',
          productType: 'Pet Supplies',
          shipQty: 100,
          cartons: 5,
          qtyPerCarton: 20,
          receivedQty: 100,
          receivedCartons: 5,
          discrepancyQty: 0,
          discrepancyTag: 'VERIFIED',
          discrepancyReason: 'FC库房查找到遗漏箱，已全额补收',
          requiresFollowup: false,
          receivedDate: relDate(-10),
          source: 'Walmart Inbound Template',
        },
      ],
    },

    // Scenario 8: 无法判断Case (发货100，接收75，Arrival Date为空 -> 存在差异但无法判断10天Case时间)
    {
      id: '2190384BHY',
      shipmentName: '2190384BHY-ATL1-2026',
      shipDate: relDate(-5),
      eta: relDate(2),
      arrivalDate: undefined, // No arrival date!
      fc: 'ATL1 (Atlanta, GA)',
      tracking: '1Z999AA10123456788',
      carrier: 'XPO Logistics',
      notes: '【场景8：无法判断Case】仅有ETA预计到仓，无实际到仓日期，禁止直接触发10天Case',
      source: 'Demo Data',
      items: [
        {
          shipmentId: '2190384BHY',
          sku: 'HOME-ORG-302',
          itemId: 'WMT-ITEM-781902',
          gtin: '008100523402',
          productName: 'Stackable Acrylic Closet Storage Bins 4-Pack',
          productType: 'Home Storage',
          shipQty: 100,
          cartons: 10,
          qtyPerCarton: 10,
          receivedQty: 0,
          receivedCartons: 0,
          discrepancyQty: 100,
          source: 'Walmart Inbound Template',
        },
      ],
    },

    // Scenario 9: 临界即将达到10天 (到仓8天，还需2天)
    {
      id: '1092837JKL',
      shipmentName: '1092837JKL-DFW1-2026',
      shipDate: relDate(-12),
      eta: relDate(-8),
      arrivalDate: relDate(-8),
      fc: 'DFW1 (Fort Worth, TX)',
      tracking: '1Z999AA10123456789',
      carrier: 'SAIA Freight',
      notes: '到仓已8天，差异25件，还需2天达到10天Case条件',
      source: 'Demo Data',
      items: [
        {
          shipmentId: '1092837JKL',
          sku: 'TECH-CAB-09',
          itemId: 'WMT-ITEM-310492',
          gtin: '008100523403',
          productName: 'Braided USB-C Fast Charging Cable (6.6ft / 2-Pack)',
          productType: 'Consumer Electronics',
          shipQty: 250,
          cartons: 10,
          qtyPerCarton: 25,
          receivedQty: 225,
          receivedCartons: 9,
          discrepancyQty: 25,
          discrepancyTag: 'FC_SHORTAGE',
          discrepancyReason: '少收1箱(25件)，已到仓8天',
          requiresFollowup: true,
          receivedDate: relDate(-6),
          source: 'Walmart Inbound Template',
        },
      ],
    },
  ];

  // Run status calculator on all demo shipments
  const shipments: Shipment[] = rawShipments.map((shp) =>
    calculateShipmentMetrics(shp as any, today, 10)
  );

  // Case records
  const cases: CaseRecord[] = [
    {
      id: 'WMT-CASE-202608-019',
      shipmentId: '4392018QRT',
      sku: 'OUT-CAMP-081',
      itemId: 'WMT-ITEM-904122',
      productName: 'Ultralight Inflatable Camping Sleeping Pad',
      discrepancyQty: 60,
      shipQty: 180,
      receivedQty: 120,
      arrivalDate: relDate(-16),
      eligibleDate: relDate(-6),
      caseOpenDate: relDate(-5),
      status: 'In Review',
      walmartResponse: 'Walmart Support: We have opened an internal investigation with MCI1 dock supervisor. POD under review.',
      resolutionQty: 0,
      finalDifference: 60,
      notes: '已上传卡车派送签收单（POD）及装箱清单',
      createdAt: relDate(-5),
      updatedAt: relDate(-1),
    },
    {
      id: 'WMT-CASE-202608-011',
      shipmentId: '3281092WZX',
      sku: 'PET1005-B-M',
      itemId: 'WMT-ITEM-550192',
      productName: 'Pet Ergonomic Mesh Dog Harness (Medium / Blue)',
      discrepancyQty: 20,
      shipQty: 100,
      receivedQty: 100,
      arrivalDate: relDate(-18),
      eligibleDate: relDate(-8),
      caseOpenDate: relDate(-7),
      status: 'Resolved',
      walmartResponse: 'Walmart FC IND1 found remaining 1 carton (20 units) in staging bay. Stock credited to Available Inventory.',
      resolutionQty: 20,
      finalDifference: 0,
      closedDate: relDate(-2),
      notes: 'Walmart已补收入库，数量差异完全消除',
      createdAt: relDate(-7),
      updatedAt: relDate(-2),
    },
    {
      id: 'WMT-CASE-202608-005',
      shipmentId: '5419208PLQ',
      sku: 'BEAUTY-OIL-50',
      itemId: 'WMT-ITEM-449102',
      productName: 'Organic Cold-Pressed Rosehip Seed Facial Oil 50ml',
      discrepancyQty: 30,
      shipQty: 150,
      receivedQty: 120,
      arrivalDate: relDate(-15),
      eligibleDate: relDate(-5),
      caseOpenDate: relDate(-4),
      status: 'Resolved',
      walmartResponse: 'Walmart Claims Department: Approved lost inventory reimbursement claim #CLM-881920. $480.00 will be credited in next bi-weekly payout.',
      resolutionQty: 30,
      finalDifference: 0,
      closedDate: relDate(-1),
      notes: 'Walmart官方全额赔付30件损失，赔偿金额 $480.00，差异不再计入待收清点',
      reimbursementStatus: 'APPROVED',
      reimbursementType: '全额赔付 (Full Claim Reimbursement)',
      reimbursedUnits: 30,
      reimbursedAmount: 480.0,
      reimbursementCurrency: 'USD',
      reimbursementNote: 'Walmart官方赔偿批准：已按成本价 $16/件 全额赔付 30 件，结算周期自动入账',
      createdAt: relDate(-4),
      updatedAt: relDate(-1),
    },
  ];

  // Inventory items
  const inventory: InventoryItem[] = [
    {
      sku: 'PET1005-B-M',
      itemId: 'WMT-ITEM-550192',
      gtin: '008100523401',
      productName: 'Pet Ergonomic Mesh Dog Harness (Medium / Blue)',
      productType: 'Pet Supplies',
      available: 165,
      reserved: 12,
      inbound: 0,
      receiving: 0,
      totalProjected: 165,
      safetyStock: 80,
      minStock: 40,
      maxStock: 500,
      targetStock: 250,
      sales30Days: 185,
      dailyAvgSales: 6.2,
      daysOfSupply: 26.6,
      lastUpdated: relDate(-1),
      source: 'Walmart Inventory Report',
    },
    {
      sku: 'HOME-ORG-302',
      itemId: 'WMT-ITEM-781902',
      gtin: '008100523402',
      productName: 'Stackable Acrylic Closet Storage Bins 4-Pack',
      productType: 'Home Storage',
      available: 48,
      reserved: 8,
      inbound: 100,
      receiving: 45,
      totalProjected: 193,
      safetyStock: 120,
      minStock: 60,
      maxStock: 600,
      targetStock: 350,
      sales30Days: 240,
      dailyAvgSales: 8.0,
      daysOfSupply: 6.0,
      lastUpdated: relDate(-1),
      source: 'Walmart Inventory Report',
    },
    {
      sku: 'TECH-CAB-09',
      itemId: 'WMT-ITEM-310492',
      gtin: '008100523403',
      productName: 'Braided USB-C Fast Charging Cable (6.6ft / 2-Pack)',
      productType: 'Consumer Electronics',
      available: 280,
      reserved: 35,
      inbound: 0,
      receiving: 45,
      totalProjected: 325,
      safetyStock: 150,
      minStock: 80,
      maxStock: 800,
      targetStock: 400,
      sales30Days: 310,
      dailyAvgSales: 10.3,
      daysOfSupply: 27.2,
      lastUpdated: relDate(-1),
      source: 'Walmart Inventory Report',
    },
    {
      sku: 'OUT-CAMP-081',
      itemId: 'WMT-ITEM-904122',
      gtin: '008100523404',
      productName: 'Ultralight Inflatable Camping Sleeping Pad',
      productType: 'Outdoor & Sports',
      available: 32,
      reserved: 4,
      inbound: 0,
      receiving: 60,
      totalProjected: 92,
      safetyStock: 50,
      minStock: 25,
      maxStock: 300,
      targetStock: 150,
      sales30Days: 75,
      dailyAvgSales: 2.5,
      daysOfSupply: 12.8,
      lastUpdated: relDate(-1),
      source: 'Walmart Inventory Report',
    },
    {
      sku: 'BEAUTY-OIL-50',
      itemId: 'WMT-ITEM-449102',
      gtin: '008100523405',
      productName: 'Organic Cold-Pressed Rosehip Seed Facial Oil 50ml',
      productType: 'Beauty & Personal Care',
      available: 110,
      reserved: 15,
      inbound: 0,
      receiving: 30,
      totalProjected: 140,
      safetyStock: 90,
      minStock: 45,
      maxStock: 450,
      targetStock: 200,
      sales30Days: 160,
      dailyAvgSales: 5.3,
      daysOfSupply: 20.8,
      lastUpdated: relDate(-1),
      source: 'Walmart Inventory Report',
    },
    {
      sku: 'KITCH-SIL-6P',
      itemId: 'WMT-ITEM-612849',
      gtin: '008100523406',
      productName: 'Heat-Resistant Silicone Cooking Utensils Set (6-Piece)',
      productType: 'Kitchen & Dining',
      available: 95,
      reserved: 10,
      inbound: 0,
      receiving: 20,
      totalProjected: 115,
      safetyStock: 100,
      minStock: 50,
      maxStock: 500,
      targetStock: 300,
      sales30Days: 195,
      dailyAvgSales: 6.5,
      daysOfSupply: 14.6,
      lastUpdated: relDate(-1),
      source: 'Walmart Inventory Report',
    },
  ];

  // Inventory Ledger Entries
  const ledger: InventoryLedgerEntry[] = [
    {
      id: 'LEDGER-001',
      date: relDate(-25),
      sku: 'PET1005-B-M',
      productName: 'Pet Ergonomic Mesh Dog Harness (Medium / Blue)',
      beforeQty: 125,
      changeQty: -25,
      afterQty: 100,
      changeType: '销售出库',
      source: 'Walmart Orders Report',
      reference: 'WMT-ORD-991023',
      timestamp: relDate(-25) + ' 14:20:00',
    },
    {
      id: 'LEDGER-002',
      date: relDate(-12),
      sku: 'PET1005-B-M',
      productName: 'Pet Ergonomic Mesh Dog Harness (Medium / Blue)',
      beforeQty: 100,
      changeQty: 100,
      afterQty: 200,
      changeType: 'Walmart接收',
      source: 'Walmart Inbound Template',
      reference: '9741694WFA',
      notes: '货件 9741694WFA 签收入库 100 件',
      timestamp: relDate(-12) + ' 09:30:15',
    },
    {
      id: 'LEDGER-003',
      date: relDate(-5),
      sku: 'PET1005-B-M',
      productName: 'Pet Ergonomic Mesh Dog Harness (Medium / Blue)',
      beforeQty: 200,
      changeQty: -35,
      afterQty: 165,
      changeType: '销售出库',
      source: 'Walmart Orders Report',
      reference: 'WMT-ORD-998812',
      timestamp: relDate(-5) + ' 18:45:00',
    },
    {
      id: 'LEDGER-004',
      date: relDate(-8),
      sku: 'HOME-ORG-302',
      productName: 'Stackable Acrylic Closet Storage Bins 4-Pack',
      beforeQty: 15,
      changeQty: 155,
      afterQty: 170,
      changeType: 'Walmart接收',
      source: 'Walmart Inbound Template',
      reference: '6528194MNO',
      notes: '货件 6528194MNO 到仓部分接收 155 件',
      timestamp: relDate(-8) + ' 11:15:30',
    },
    {
      id: 'LEDGER-005',
      date: relDate(-3),
      sku: 'HOME-ORG-302',
      productName: 'Stackable Acrylic Closet Storage Bins 4-Pack',
      beforeQty: 170,
      changeQty: -122,
      afterQty: 48,
      changeType: '销售出库',
      source: 'Walmart Orders Report',
      reference: 'WMT-ORD-999014',
      timestamp: relDate(-3) + ' 20:00:00',
    },
    {
      id: 'LEDGER-006',
      date: relDate(-6),
      sku: 'TECH-CAB-09',
      productName: 'Braided USB-C Fast Charging Cable (6.6ft / 2-Pack)',
      beforeQty: 55,
      changeQty: 225,
      afterQty: 280,
      changeType: 'Walmart接收',
      source: 'Walmart Inbound Template',
      reference: '1092837JKL',
      notes: '货件 1092837JKL 到仓接收 225 件',
      timestamp: relDate(-6) + ' 16:10:00',
    },
  ];

  return {
    shipments,
    inventory,
    ledger,
    cases,
    products,
  };
}

export function generateDemoFreightData(): {
  items: any[];
  actuals: Record<string, any>;
} {
  const items = [
    // 1. July 2026 Shipments (2026/7/26) - Mixed Box Scenario
    {
      id: 'F-ITEM-001',
      shipmentId: '6520194CAS',
      warehouse: 'OAK4',
      shipDate: '2026-07-26',
      monthKey: '2026-07',
      sku: 'PET1005-B-M',
      productName: 'Pet Ergonomic Mesh Dog Harness (Medium / Blue)',
      actualQty: 100,
      boxCount: 1,
      boxWeight: 13.56,
      boxLength: 43,
      boxWidth: 25,
      boxHeight: 37,
      dimensionsText: '43*25*37',
      channel: '美森限时达',
      unitPrice: 13.5,
      isMergedCustoms: false,
      customsDeclarationType: 'STANDALONE',
      mixedBoxGroup: 'MIX-01',
      volumetricWeight: 6.63,
      billedWeightPerBox: 13.56,
      pricingMethod: 'Weight' as const,
      minWeightApplied: false,
      estimatedItemFreight: 183.06,
      notes: '与 TECH-CAB-09, BEAUTY-OIL-50 混装为1箱 (MIX-01)',
    },
    {
      id: 'F-ITEM-002',
      shipmentId: '6520194CAS',
      warehouse: 'OAK4',
      shipDate: '2026-07-26',
      monthKey: '2026-07',
      sku: 'TECH-CAB-09',
      productName: 'Braided USB-C Fast Charging Cable (6.6ft / 2-Pack)',
      actualQty: 80,
      boxCount: 1,
      boxWeight: 13.56,
      boxLength: 43,
      boxWidth: 25,
      boxHeight: 37,
      dimensionsText: '43*25*37',
      channel: '美森限时达',
      unitPrice: 13.5,
      isMergedCustoms: false,
      customsDeclarationType: 'STANDALONE',
      mixedBoxGroup: 'MIX-01',
      volumetricWeight: 6.63,
      billedWeightPerBox: 13.56,
      pricingMethod: 'Weight' as const,
      minWeightApplied: false,
      estimatedItemFreight: 183.06,
      notes: '混箱装 (MIX-01，整箱运费计一次)',
    },
    {
      id: 'F-ITEM-003',
      shipmentId: '6520194CAS',
      warehouse: 'OAK4',
      shipDate: '2026-07-26',
      monthKey: '2026-07',
      sku: 'BEAUTY-OIL-50',
      productName: 'Organic Cold-Pressed Rosehip Seed Facial Oil 50ml',
      actualQty: 50,
      boxCount: 1,
      boxWeight: 13.56,
      boxLength: 43,
      boxWidth: 25,
      boxHeight: 37,
      dimensionsText: '43*25*37',
      channel: '美森限时达',
      unitPrice: 13.5,
      isMergedCustoms: false,
      customsDeclarationType: 'STANDALONE',
      mixedBoxGroup: 'MIX-01',
      volumetricWeight: 6.63,
      billedWeightPerBox: 13.56,
      pricingMethod: 'Weight' as const,
      minWeightApplied: false,
      estimatedItemFreight: 183.06,
      notes: '混箱装 (MIX-01，整箱运费计一次)',
    },
    {
      id: 'F-ITEM-004',
      shipmentId: '6520194CAS',
      warehouse: 'OAK4',
      shipDate: '2026-07-26',
      monthKey: '2026-07',
      sku: 'HOME-ORG-302',
      productName: 'Stackable Acrylic Closet Storage Bins 4-Pack',
      actualQty: 120,
      boxCount: 6,
      boxWeight: 15.0,
      boxLength: 50,
      boxWidth: 40,
      boxHeight: 30,
      dimensionsText: '50*40*30',
      channel: '美森限时达',
      unitPrice: 13.5,
      isMergedCustoms: false,
      customsDeclarationType: 'STANDALONE',
      volumetricWeight: 10.0,
      billedWeightPerBox: 15.0,
      pricingMethod: 'Weight' as const,
      minWeightApplied: false,
      estimatedItemFreight: 1215.0,
      notes: '独立整箱，6箱*15kg*13.5元/kg',
    },

    // 2. July 2026 - Standalone Customs + <12kg Minimum Rule Scenario
    {
      id: 'F-ITEM-005',
      shipmentId: '5410982JFK',
      warehouse: 'EWR4',
      shipDate: '2026-07-15',
      monthKey: '2026-07',
      sku: 'TECH-CAB-09',
      productName: 'Braided USB-C Fast Charging Cable (6.6ft / 2-Pack)',
      actualQty: 300,
      boxCount: 15,
      boxWeight: 8.5,
      boxLength: 38,
      boxWidth: 28,
      boxHeight: 22,
      dimensionsText: '38*28*22',
      channel: '空运专线',
      unitPrice: 38.0,
      isMergedCustoms: false, // 独立报关 350
      volumetricWeight: 3.9,
      billedWeightPerBox: 12.0, // 实重8.5 < 12kg -> 保底12kg
      pricingMethod: 'Weight' as const,
      minWeightApplied: true,
      estimatedItemFreight: 6840.0,
      notes: '单箱重8.5kg不足12kg，触发保底12kg计费',
    },

    // 3. August 2026 - Scenario 1 Shipment (9741694WFA)
    {
      id: 'F-ITEM-006',
      shipmentId: '9741694WFA',
      warehouse: 'PHX1',
      shipDate: '2026-08-11',
      monthKey: '2026-08',
      sku: 'PET1005-B-M',
      productName: 'Pet Ergonomic Mesh Dog Harness (Medium / Blue)',
      actualQty: 100,
      boxCount: 5,
      boxWeight: 11.2,
      boxLength: 45,
      boxWidth: 35,
      boxHeight: 30,
      dimensionsText: '45*35*30',
      channel: '美森限时达',
      unitPrice: 14.5,
      isMergedCustoms: true,
      volumetricWeight: 7.88,
      billedWeightPerBox: 12.0, // 实重11.2 < 12kg -> 12kg
      pricingMethod: 'Weight' as const,
      minWeightApplied: true,
      estimatedItemFreight: 870.0,
      notes: '单箱实重11.2kg按保底12kg计费，合并报关175元',
    },

    // 4. August 2026 - Scenario 2 Shipment (8839201KDL)
    {
      id: 'F-ITEM-007',
      shipmentId: '8839201KDL',
      warehouse: 'IND1',
      shipDate: '2026-08-23',
      monthKey: '2026-08',
      sku: 'KITCH-SIL-6P',
      productName: 'Heat-Resistant Silicone Cooking Utensils Set (6-Piece)',
      actualQty: 100,
      boxCount: 10,
      boxWeight: 14.0,
      boxLength: 40,
      boxWidth: 30,
      boxHeight: 35,
      dimensionsText: '40*30*35',
      channel: '以星快船',
      unitPrice: 12.0,
      isMergedCustoms: false, // 独立报关 350
      volumetricWeight: 7.0,
      billedWeightPerBox: 14.0,
      pricingMethod: 'Weight' as const,
      minWeightApplied: false,
      estimatedItemFreight: 1680.0,
      notes: '实重14kg计费，独立报关350元',
    },

    // 5. August 2026 - Scenario 3 Shipment (7619283TXA) - Volumetric Weight > Actual Weight
    {
      id: 'F-ITEM-008',
      shipmentId: '7619283TXA',
      warehouse: 'DFW6',
      shipDate: '2026-08-28',
      monthKey: '2026-08',
      sku: 'OUT-CAMP-081',
      productName: 'Ultralight Inflatable Camping Sleeping Pad',
      actualQty: 100,
      boxCount: 10,
      boxWeight: 10.0,
      boxLength: 55,
      boxWidth: 45,
      boxHeight: 35,
      dimensionsText: '55*45*35',
      channel: '普船超大件',
      unitPrice: 9.5,
      isMergedCustoms: true,
      volumetricWeight: 14.44, // 55*45*35/6000 = 14.44 > 10.0
      billedWeightPerBox: 14.44,
      pricingMethod: 'Volume' as const,
      minWeightApplied: false,
      estimatedItemFreight: 1371.8,
      notes: '单箱体积重14.44kg > 实重10.0kg，按体积重计费',
    },

    // 6. August 2026 - Mixed Box 2 (4390192LGB)
    {
      id: 'F-ITEM-009',
      shipmentId: '4390192LGB',
      warehouse: 'LAX9',
      shipDate: '2026-08-29',
      monthKey: '2026-08',
      sku: 'BEAUTY-OIL-50',
      productName: 'Organic Cold-Pressed Rosehip Seed Facial Oil 50ml',
      actualQty: 60,
      boxCount: 2,
      boxWeight: 15.2,
      boxLength: 42,
      boxWidth: 32,
      boxHeight: 28,
      dimensionsText: '42*32*28',
      channel: '美森限时达',
      unitPrice: 14.0,
      isMergedCustoms: false,
      customsDeclarationType: 'STANDALONE',
      mixedBoxGroup: 'MIX-02',
      volumetricWeight: 6.27,
      billedWeightPerBox: 15.2,
      pricingMethod: 'Weight' as const,
      minWeightApplied: false,
      estimatedItemFreight: 425.6,
      notes: '与 TECH-CAB-09 混装2箱 (MIX-02)',
    },
    {
      id: 'F-ITEM-010',
      shipmentId: '4390192LGB',
      warehouse: 'LAX9',
      shipDate: '2026-08-29',
      monthKey: '2026-08',
      sku: 'TECH-CAB-09',
      productName: 'Braided USB-C Fast Charging Cable (6.6ft / 2-Pack)',
      actualQty: 120,
      boxCount: 2,
      boxWeight: 15.2,
      boxLength: 42,
      boxWidth: 32,
      boxHeight: 28,
      dimensionsText: '42*32*28',
      channel: '美森限时达',
      unitPrice: 14.0,
      isMergedCustoms: false,
      customsDeclarationType: 'STANDALONE',
      mixedBoxGroup: 'MIX-02',
      volumetricWeight: 6.27,
      billedWeightPerBox: 15.2,
      pricingMethod: 'Weight' as const,
      minWeightApplied: false,
      estimatedItemFreight: 425.6,
      notes: '混箱装 (MIX-02，2箱只计一次运费)',
    },
  ];

  const actuals: Record<string, any> = {
    '6520194CAS': {
      actualChargeableWeight: 103.56,
      actualCost: 1573.06,
      actualUnitPrice: 13.5,
      actualCustomsFee: 175,
      reconciliationNotes: '美森7月出货账单核对一致，已完成平账',
      isSyncedToShipments: true,
    },
    '5410982JFK': {
      actualChargeableWeight: 180.0,
      actualCost: 7190.0,
      actualUnitPrice: 38.0,
      actualCustomsFee: 350,
      reconciliationNotes: '空运专线账单已核销，按12kg/箱保底结算',
      isSyncedToShipments: true,
    },
    '9741694WFA': {
      actualChargeableWeight: 60.0,
      actualCost: 1045.0,
      actualUnitPrice: 14.5,
      actualCustomsFee: 175,
      reconciliationNotes: '8月第一批账单核对一致',
      isSyncedToShipments: true,
    },
    '8839201KDL': {
      actualChargeableWeight: 148.0,
      actualCost: 2126.0,
      actualUnitPrice: 12.0,
      actualCustomsFee: 350,
      reconciliationNotes: '物流实际称重增加8kg托盘重，费用超支96元',
      isSyncedToShipments: true,
    },
  };

  return { items, actuals };
}

